export const splashes = [
    "Wdym 'this.func is not a function'!?",
    "[object Object]",
    "WOO!",
    "[object JSON]",
    "1+1 isn't 2, you've probably been gaslit!",
    "What's a bit reverse? The only thing I know is a line break.",
    "The G",
    "Wait, Why is there a math constant named SQRT1_2? Just run Math.sqrt(1/2)?",
    "Imagine if this website completely broke 💀",
    `DIE! <i>throws die...</i> a ${Math.floor(Math.random() * 6)+1}!`,
    "Fun fact: The 16 bit integer limit will overflow and corrupt the javascript.<br>Never enter 65535 as it will crash the page.",
    "Go away, exotic modes and functions! GO AWAY!",
    "I don't think the whale would <i>swear</i> over air conditioning...",
    "The initramfs will completely freak out the linting.",
    "POV: \" 'use strict'; 0765 \" 💀💀💀 bruh",
    "THE 64 BIT INTEGER LIMIT WILL COLLAPSE AND DESTROY THE MINCERAFT",
    "THE X86_64<br>IS A 64 BIT VERSION OF INTEL'S X86 CPU, CREATED BY AMD I THINK<br>I DON'T KNOW HOW TO WORD THAT SO IT DOESN'T SOUND AWKWARD<br>THE ODD HYPERBOLA LIMIT WILL COLLAPE AND OBSERVE THE WAVE FUNCTION",
    "0x8F rawr :3",
    "Something to do with an indie video game... Oops, I forgor.",
    "the nixos files will be unpacked and corrupt the router.<br>Seriously, NixOS installation unplugged it.",
    "Dum de bum!",
    "The infinite loop will EAT YOUR PROCESSOR AND MEMORY!!!1!",
    "There's a really cool glitch in that one game. But I forgot the numbers... Guess they're missing.",
    "<i>*SCREAMING*</i>",
    "Laughl.",
    "Spot the references in these splashtexts!",
    "Metal pipe moment",
    'See an issue? <a href="https://github.com/Chasyxx/EnBeat_NEW/issues" target="_blank">Let me know!!</a>',
    "<i>A TypeScript (TS) enum is a special type in TypeScript that allows you to define a set of named constants. Enums can be thought of as a collection of related values that are easier to read and maintain than plain strings or numbers. They can be used to improve the readability of your code by providing a set of clear, distinct values that can be used in place of numbers or strings.</i><br> &mdash;ChatGPT",
    "wth what is this text above me",
    "I dunno, man, I <i>might</i> have eighty televisions, but if I do, <i>they're all 1080p!</i>",
    "Reject all else, 8 bit computing is the way!",
    "Windows systems when you remove system32 -> :(",
    "The creator of this website uses Arch Linux, and they'd like to let you anow of that fact.",
    "Where's my pet eldrich horror now?",
    "galvanize that steel and squAre it",
    "Sorry, maximum call stack size exceeded!",
    "Segmentation fault (core dumped)",
    "Aborted (core dumped)",
    "Quit (core dumped)",
    "It looks like your program tried to read a part of memory that wasn't allocated to it.<br>Thankfully, the state when it did that was preserved, which you can use to fix the obvious bug.<br><br>TL;DR Segmentation fault (core dumped)<br><br>you@yourcomputer ~$",
    "But you can call it DOLLCHAN++",
    "But you can call it DOLLCHAN#",
    "Concieved in 2022!",
    "Revived in 202<b>5</b>!",
    "We're back! Dang...",
    "Woo, r/bytebeat!",
    "Woo, dollchan.net/btb!",
    "Woo, older iteration!",
    "Woo, landing page!",
    "Woo, bytetable!",
    "Woo, dollchan!",
    "Woo, sArpnt!",
    "The old legacy version has a huge bug that can rickroll you.",
    "Back with what you want! Or, at least what <b><i>I</i></b> want.",
    "Creator of Diagram! (Not combined)",
    "Creator &mdash; and DESTROYER &mdash; of triads!",
    "Creator of the zoom indicator!",
    "96kHz samplerate!",
    "Cookie?",
    "Change is OK!",
    "Expand your mind, OMORI!",
    "Expand!",
    "spooky scary skeletions<br>send shivers down your spine<br><br>shrieking skulls will shock your soul<br>seal your fate tonight",
    "Check out the <a href='https://www.youtube.com/watch?v=dQw4w9WgXcQ' target='_blank'>user manual!</a>",
    "Error 40!<br>The page has detected a critical error and will now combust!",
    "&quot;As hard as it may be, sometimes you have to leave from what leaves you in a worse place.&quot;<br> &mdash; Chasyxx, 2025",
    "&quot;As hard as it is, anything can disappear when you are least prepared.&quot;<br> &mdash; Chasyxx, 2025",
    "RIP Bytebeat Classic Discord<br>Gone without warning...<br>2022 - 2025"
];